import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideBar from "./component/SideBar";
import { SessionProvider } from "./component/SessionProvider";
import { SiteProvider } from "./component/context/SiteContext";
import { FilterProvider } from "./FilterContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProvider>
          <FilterProvider>
            <SiteProvider> {/* A terme Site provider viendra de filter provider */}
              <div className="flex h-screen"> {/* Utiliser h-screen pour remplir la hauteur de l'écran */}
                <SideBar className_props="min-h-full" /> {/* Assurer que la sidebar prend toute la hauteur */}
                <main className="flex-1 overflow-y-auto"> {/* Le contenu principal avec un défilement si nécessaire */}
                  {children}
              </main>
            </div>
            </SiteProvider>
          </FilterProvider>
        </SessionProvider>  
      </body>
    </html>
  );
}